"""add columns to contest table

Revision ID: cedf588f1442
Revises: 4a6defb4af2a
Create Date: 2023-03-09 12:25:10.936176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cedf588f1442'
down_revision = '4a6defb4af2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('complexity', sa.Integer(), nullable=True))
    op.add_column('contests', sa.Column('topic', sa.String(), nullable=False))
    op.add_column('topics', sa.Column('problem_number', sa.String(), nullable=False))
    op.drop_constraint('topics_problem_id_fkey', 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'problems', ['problem_number'], ['number'])
    op.drop_column('topics', 'problem_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key('topics_problem_id_fkey', 'topics', 'problems', ['problem_id'], ['id'])
    op.drop_column('topics', 'problem_number')
    op.drop_column('contests', 'topic')
    op.drop_column('contests', 'complexity')
    # ### end Alembic commands ###
